version: 2
updates:
  # Quarkus branch dependencies
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
    target-branch: quarkus

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    target-branch: quarkus

  # Main branch dependencies
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
    target-branch: main

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    target-branch: main